<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5e9773722e89d',
		'title' => 'Ambulatorio',
		'fields' => array(
			array(
				'key' => 'field_5e977394b235a',
				'label' => 'Prestazioni in Convenzione',
				'name' => 'prestazioni_in_convenzione',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'prestazioni-ambulatoriali',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'add_term' => 1,
				'save_terms' => 1,
				'load_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array(
				'key' => 'field_5e977417b235b',
				'label' => 'Prestazioni a pagamento',
				'name' => 'prestazioni_a_pagamento',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'prestazioni-ambulatoriali',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'add_term' => 1,
				'save_terms' => 1,
				'load_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array(
				'key' => 'field_5f0eb4067b3e2',
				'label' => 'Prestazioni',
				'name' => 'prestazioni',
				'type' => 'taxonomy',
				'instructions' => 'Elenco completo delle prestazioni',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'prestazioni-ambulatoriali',
				'field_type' => 'multi_select',
				'allow_null' => 0,
				'add_term' => 1,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array(
				'key' => 'field_5f0eb9688dd7f',
				'label' => 'Ubicazione',
				'name' => 'ubicazione',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'ambulatori',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'permalink',
			1 => 'the_content',
			2 => 'excerpt',
			3 => 'discussion',
			4 => 'comments',
			5 => 'slug',
			6 => 'format',
			7 => 'page_attributes',
			8 => 'featured_image',
			9 => 'categories',
			10 => 'tags',
			11 => 'send-trackbacks',
		),
		'active' => true,
		'description' => '',
	));
	
	endif;